version: '2'

services:
  ex2-server:
    container_name: ex2-Server
    image: ex2-server
    ports:
      - "16001:16001"
    depends_on:
      - ex1-server
    links:
      - ex1-server
  ex1-server:
    container_name: ex1-Server
    image: ex1-server
    ports:
      - "16000:16000"
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    container_name: mongo-server
    image: mongo:latest
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - ./contratos2024.json:/datasets/contratos2024.json
    command: mongoimport --host mongodb -d contratos -c contratos --type json --file /datasets/contratos2024.json --jsonArray